#!/bin/bash
case "$1" in
    remove|purge)
        update-desktop-database /usr/share/applications > /dev/null 2>&1 || true
        update-icon-caches /usr/share/icons/hicolor > /dev/null 2>&1 || true
        ;;
esac
